repos:
  - repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.81.0 # The version of cfn-lint to use
    hooks:
    - id: cfn-lint
      files: cloudformation/.*\.(json|yml|yaml)$
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.83.5"
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
      - id: terraform_validate
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--config", "./.terraform-docs.yaml", "--recursive", "--output-file", "README.md", "./"]
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '2.5.11'
    hooks:
      - id: checkov
        verbose: false
