name: Dev Build and Deploy Fargate Container
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  deploy:
    name: Deploy TESTING
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Create tags
        id: tags
        run: |
          if [ $GITHUB_EVENT_NAME = "workflow_dispatch" ]; then
            TAG_SHA=$(echo $GITHUB_SHA | cut -c 1-8)
          else
            TAG_SHA=$(echo ${{ github.event.pull_request.head.sha }} | cut -c 1-8)
          fi
          if [ $GITHUB_EVENT_NAME = "workflow_dispatch" ]; then
            TAG_PR=$GITHUB_EVENT_NAME
          else
            TAG_PR=$(echo "PR-"${{ github.event.pull_request.number }})
          fi
          echo "::set-output name=tag_sha::$TAG_SHA"
          echo "::set-output name=tag_pr::$TAG_PR"

      - name: Show tags
        run: |
          TAG_SHA="${{ steps.tags.outputs.tag_sha }}"
          TAG_PR="${{ steps.tags.outputs.tag_pr }}"
          echo $TAG_SHA
          echo $TAG_PR
