name: pre-commit
on:
    push:
        branches-ignore: [main,stage]

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
        - uses: pre-commit/action@v3.0.1
          with:
            extra_args: terraform-docs-go --all-files
