name: Dev Build and Deploy Fargate Container
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  deploy:
    name: Deploy TESTING
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - name: Show Docker Tags
        run: |
          echo ${{ github.event.pull_request.head.sha }} | cut -c 1-8
          echo "PR-"${{ github.event.pull_request.number }}
