name: Prod Promote TESTING
on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy TESTING
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Show Docker Tags
        run: |
          echo $GITHUB_SHA | cut -c 1-8
          echo ${{ github.event.release.tag_name }}
