name: Shared Prod Promote TESTING
on:
  workflow_dispatch:
  release:
    types: [published]

permissions: read-all

jobs:
    deploy:
      name: Shared Prod Container Promote
      uses: cabutlermit/.github/.github/workflows/shared-prod-promote.yml@main
      secrets: inherit
      with:
        VAR_ONE: "ij7jh7g9"
        VAR_TWO: "second variable"
