name: Stage Build and Deploy Fargate Container
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

permissions: read-all

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Deploy TESTING
    runs-on: ubuntu-latest
    steps:
      - name: Show values
        run: |
          echo ${{ github.ref }}
          echo ${{ github.event.release.target_commitish }}

      - uses: actions/checkout@v4

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Show Docker Tags
        run: |
          echo ${{ github.event.head_commit.id }} | cut -c 1-8
          echo $GITHUB_EVENT_NAME
          echo $GITHUB_SHA
