name: Stage Build and Deploy Fargate Container
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      
jobs:
  deploy:
    name: Deploy TESTING
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
